Develop
hheiress/OCCycling pull request #3
Opened 2021-02-02 19:55 UTC by Jose-cod7

2021-02-04 18:19 UTC, nandanrao requested changes
Muy bien, chicos y chicas!! Me gusta. He dejado varios comentarios. El mas importante es: añade el node_modules al gitignore, porfa!!!

2021-02-04 18:19 UTC, nandanrao commented on Front-end/src/components/Bicycles/Bicycles.js
> +      fetch("http://localhost:3000/bikes")
1. Poned un `catch`!! 
2. Aseguraos que el backend está siempre enviando JSON o controlar esto tb!

2021-02-04 18:19 UTC, nandanrao commented on Front-end/src/components/Rentings/RentBicycle.js
> +      fetch("http://localhost:3000/bikes")
Veo este URL hardcoded en muchos sitios diferent. Igual se pueder poner en un sitio para que sea mas facil cambiar luego?

2021-02-04 18:19 UTC, nandanrao commented on Front-end/src/components/Residents/Residents.js
> +const AllRenters = props => {
FilterRenters y AllRenters me parecen componentes muy parecidos....se puede hacer mas DRY?

2021-02-04 18:19 UTC, nandanrao commented on back-end/controllers/bikes.js
> +            res.status(500).send("Internal Server Error")
Si vas a enviar un 500, que es un error general, porque no dar el error al "next"? Mira la seccion de "The default error handler":  http://expressjs.com/en/guide/error-handling.html

2021-02-04 18:19 UTC, nandanrao commented on back-end/controllers/users.js
> +ctrl.post("/", function (req, res) {
Todos tus `ctrl.get` y todos tus `ctrl.post` me parecen igualitos. Igual se puede hacer mas DRY?

2021-02-06 14:05 UTC, nandanrao reviewed
Estos cambios me paracen bien!

2021-02-09 11:54 UTC, Jose-cod7 commented on back-end/controllers/bikes.js
> +            res.status(500).send("Internal Server Error")
He agreagado un error handler para enviar  un 500 y un 404, lo hice asi por la verdad no entendi como usar el "default error handler" 😄 pero de esta forma esta mas pro jaja

2021-02-23 14:39 UTC, merged